[workspace]
members = [
    "common",
    "server", 
    "client"
]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/WithoutAName25/minesweeper"
homepage = "https://github.com/WithoutAName25/minesweeper"

[workspace.dependencies]
minesweeper-common = { path = "common", version = "1.0.0" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
tokio-tungstenite = { version = "0.27", features = ["rustls-tls-webpki-roots"] }
tokio-test = "0.4"
uuid = { version = "1.18.1", features = ["serde", "v4"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
futures-util = "0.3"
reqwest = { version = "0.12", features = ["charset", "http2", "json", "rustls-tls"], default-features = false }
url = "2.5"
dashmap = "6.1.0"
nanoid = "0.4.0"
rand = "0.9.2"
rocket = { version = "0.5.1", features = ["json"] }
rocket_cors = "0.6.0"
rocket_ws = "0.1.1"
thiserror = "2.0.20"
