[package]
name = "minesweeper-common"
version = "1.0.0"
edition = "2024"
description = "Shared types and protocol definitions for minesweeper client/server"

[dependencies]
serde = { workspace = true }